ALTER TABLE "TeacherSubjectRule" ADD COLUMN IF NOT EXISTS "maxSections" INTEGER;
ALTER TABLE "TeacherSubjectRule" ADD COLUMN IF NOT EXISTS "maxWeeklyHours" DOUBLE PRECISION;
ALTER TABLE "TeacherSubjectRule" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
